**Level 1 – Beginner (1–30)**

In [2]:
# 1. Load the dataset and print the shape, column names, and data types.

import pandas as pd
import numpy as np
data=pd.read_csv("/content/Advanced_Dirty_Sales_Dataset.csv")

data.shape

(44130, 12)

In [7]:
data.columns

Index(['OrderID', 'CustomerID', 'CustomerName', 'Product', 'Category',
       'Quantity', 'Price', 'OrderDate', 'City', 'Region', 'Returned',
       'TotalAmount'],
      dtype='object')

In [8]:

data.dtypes

OrderID           int64
CustomerID      float64
CustomerName     object
Product          object
Category         object
Quantity         object
Price            object
OrderDate        object
City             object
Region           object
Returned         object
TotalAmount      object
dtype: object

In [9]:
#2. Show the first 10 and last 10 rows of the dataset.
data.head(10)

,OrderID,CustomerID,CustomerName,Product,Category,Quantity,Price,OrderDate,City,Region,Returned,TotalAmount
0,44770,8192.0,@ charlie !,Keyboard,Electronics,1,$870.54,32/13/2023,PHOENIX#123,South,False,870.54
1,23355,9138.0,@ charlie !,Monitor,Electronics,5,$144.02,05-02-2024,HOUSTON#123,West,False,720.1
2,75847,4098.0,@ charlie !,Laptop,Accessories,3,$557.79,11/08/2024,NEW YORK#123,East,False,1673.37
3,95176,2391.0,@ eva !,Monitor,Electronics,5,$552.2,32/13/2023,CHICAGO#123,North,False,2761.0
4,1854,8842.0,@ eva !,Laptop,Accessories,4,$411.2,32/13/2023,CHICAGO#123,East,False,1644.8
5,56788,6935.0,@ david !,Monitor,Electronics,1,$415.12,"October 06, 2024",LOS ANGELES#123,West,False,415.12
6,63473,2787.0,@ bob !,Tablet,Electronics,3,$677.7,"April 03, 2024",PHOENIX#123,West,False,2033.1
7,79506,3389.0,@ alice !,Phone,Accessories,9,$674.73,"July 14, 2024",HOUSTON#123,North,True,6072.57
8,55148,1287.0,@ david !,Laptop,Accessories,2,$330.38,09-01-2024,HOUSTON#123,East,False,660.76
9,24564,3745.0,@ bob !,Tablet,Accessories,8,$686.34,23/04/2023,PHOENIX#123,North,False,5490.72

In [10]:
data.tail(10)

,OrderID,CustomerID,CustomerName,Product,Category,Quantity,Price,OrderDate,City,Region,Returned,TotalAmount
44120,79195,2731.0,@ bob !,Monitor,Electronics,4,$226.47,"May 31, 2024",CHICAGO#123,North,False,905.88
44121,41467,2545.0,@ david !,Keyboard,Electronics,6,$550.09,04/03/2023,CHICAGO#123,North,False,3300.54
44122,78660,3353.0,@ david !,Laptop,Electronics,7,$306.59,32/13/2023,PHOENIX#123,East,True,2146.13
44123,13142,1256.0,@ bob !,Tablet,Accessories,2,$1356.26,32/13/2023,NEW YORK#123,South,False,2712.52
44124,4013,1142.0,@ eva !,Keyboard,Electronics,6,$960.8,12-10-2023,PHOENIX#123,North,False,5764.799999999999
44125,9583,7107.0,@ bob !,Tablet,NaN,4,$856.88,32/13/2023,HOUSTON#123,North,False,3427.52
44126,47952,8896.0,@ alice !,Phone,Electronics,7,$975.64,06/08/2023,LOS ANGELES#123,East,False,6829.48
44127,48434,1731.0,@ eva !,Tablet,Electronics,3,$1286.92,"August 27, 2024",PHOENIX#123,East,False,3860.76
44128,52233,2746.0,@ alice !,Laptop,Electronics,7,$1004.99,12-21-2023,LOS ANGELES#123,North,True,7034.93
44129,3136,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
#3. Convert OrderDate to datetime type.
data['OrderDate'] = pd.to_datetime(data['OrderDate'], errors='coerce')

/tmp/ipython-input-2067425159.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data['OrderDate'] = pd.to_datetime(data['OrderDate'], errors='coerce')

In [12]:
#4. Display the total number of unique customers.

data["CustomerID"].nunique()

8930

In [13]:
#5. Show all unique product categories and count them.
data["Category"].unique()

array(['Electronics', 'Accessories', nan], dtype=object)

In [14]:
data["Category"].nunique()

2

In [15]:
data.columns

Index(['OrderID', 'CustomerID', 'CustomerName', 'Product', 'Category',
       'Quantity', 'Price', 'OrderDate', 'City', 'Region', 'Returned',
       'TotalAmount'],
      dtype='object')

In [16]:
#6. Filter all orders made in the city of "Los Angeles".
print(data[data['City'].str.contains("Los Angeles", case=False, na=False)])

       OrderID  CustomerID CustomerName   Product     Category Quantity  \
5        56788      6935.0    @ david !   Monitor  Electronics        1
18       86339      3999.0      @ eva !    Laptop  Electronics        9
19       64556      4509.0  @ charlie !    Laptop  Electronics        1
21       87250      2818.0    @ alice !     Phone  Electronics        3
25       79725      5498.0      @ eva !    Tablet  Electronics        1
...        ...         ...          ...       ...          ...      ...
44104    61744      1720.0  @ charlie !    Laptop  Accessories        3
44118    37591      1436.0  @ charlie !    Laptop  Electronics        9
44119    52690      8126.0    @ alice !  Keyboard  Accessories        9
44126    47952      8896.0    @ alice !     Phone  Electronics        7
44128    52233      2746.0    @ alice !    Laptop  Electronics        7

          Price  OrderDate             City Region Returned TotalAmount
5       $415.12 2024-10-06  LOS ANGELES#123   West    False      415.12
18     $1070.42 2024-04-29  LOS ANGELES#123   West    False     9633.78
19     $1093.26 2024-05-21  LOS ANGELES#123   East    False     1093.26
21     $1188.93 2024-02-27  LOS ANGELES#123  North     True     3566.79
25      $686.06 2023-09-24  LOS ANGELES#123  North    False      686.06
...         ...        ...              ...    ...      ...         ...
44104   $914.03 2024-03-11  LOS ANGELES#123  South    False     2742.09
44118   $966.02 2024-03-06  LOS ANGELES#123  South    False     8694.18
44119   $104.98 2023-01-09  LOS ANGELES#123  South    False      944.82
44126   $975.64 2023-06-08  LOS ANGELES#123   East    False     6829.48
44128  $1004.99 2023-12-21  LOS ANGELES#123  North     True     7034.93

[8490 rows x 12 columns]

In [17]:
#7. Select orders where quantity is more than 5.
data["Quantity"]=pd.to_numeric(data["Quantity"],errors='coerce')
more_than_5=data[data["Quantity"] > 5]
more_than_5

,OrderID,CustomerID,CustomerName,Product,Category,Quantity,Price,OrderDate,City,Region,Returned,TotalAmount
7,79506,3389.0,@ alice !,Phone,Accessories,9.0,$674.73,2024-07-14,HOUSTON#123,North,True,6072.57
9,24564,3745.0,@ bob !,Tablet,Accessories,8.0,$686.34,2023-04-23,PHOENIX#123,North,False,5490.72
13,69640,1481.0,@ bob !,Phone,Accessories,6.0,$173.41,2023-11-26,HOUSTON#123,West,False,1040.46
17,23495,1514.0,@ bob !,Tablet,Electronics,9.0,$212.04,2023-07-09,CHICAGO#123,East,False,1908.36
18,86339,3999.0,@ eva !,Laptop,Electronics,9.0,$1070.42,2024-04-29,LOS ANGELES#123,West,False,9633.78
...,...,...,...,...,...,...,...,...,...,...,...,...
44121,41467,2545.0,@ david !,Keyboard,Electronics,6.0,$550.09,2023-04-03,CHICAGO#123,North,False,3300.54
44122,78660,3353.0,@ david !,Laptop,Electronics,7.0,$306.59,NaT,PHOENIX#123,East,True,2146.13
44124,4013,1142.0,@ eva !,Keyboard,Electronics,6.0,$960.8,2023-12-10,PHOENIX#123,North,False,5764.799999999999
44126,47952,8896.0,@ alice !,Phone,Electronics,7.0,$975.64,2023-06-08,LOS ANGELES#123,East,False,6829.48
44128,52233,2746.0,@ alice !,Laptop,Electronics,7.0,$1004.99,2023-12-21,LOS ANGELES#123,North,True,7034.93

In [18]:
#8. Add a new column UnitTotal = Quantity * Price and compare with TotalAmount. Flag mismatches.

In [19]:
#9. Create a new column DiscountApplied (True if UnitTotal > TotalAmount).

In [20]:
#10.Drop the column DiscountApplied after saving it to a variable.

In [21]:
#11. Filter all returned orders.
print(data[data["Returned"]=="True"])

Empty DataFrame
Columns: [OrderID, CustomerID, CustomerName, Product, Category, Quantity, Price, OrderDate, City, Region, Returned, TotalAmount]
Index: []

In [22]:
data.nunique()

OrderID         44113
CustomerID       8930
CustomerName        5
Product             5
Category            2
Quantity            9
Price           37434
OrderDate         731
City                5
Region              4
Returned            2
TotalAmount     41882
dtype: int64

In [23]:
#12. Show top 5 cities by number of orders.
data["City"].value_counts()[:5]

City
PHOENIX#123        8818
NEW YORK#123       8714
CHICAGO#123        8711
HOUSTON#123        8565
LOS ANGELES#123    8490
Name: count, dtype: int64

In [24]:
#13. What are the top 3 most sold products (by quantity)?
data["Product"].value_counts()[:3]

Product
Phone       8718
Keyboard    8686
Laptop      8683
Name: count, dtype: int64

In [25]:
#14. Rename CustomerName to CustName and revert it.
data.rename(columns={"CustomerName":"CustName"},inplace=True)
data.columns

Index(['OrderID', 'CustomerID', 'CustName', 'Product', 'Category', 'Quantity',
       'Price', 'OrderDate', 'City', 'Region', 'Returned', 'TotalAmount'],
      dtype='object')

In [26]:
#15.Check and count missing values in each column.
data.isnull().sum()

OrderID           0
CustomerID        1
CustName          1
Product         893
Category        879
Quantity        448
Price           448
OrderDate      8801
City            832
Region            1
Returned          1
TotalAmount       1
dtype: int64

In [27]:
#16. Fill missing values in City (if any) with "Unknown".
data["City"].fillna("Unknown",inplace=True)

/tmp/ipython-input-851635615.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["City"].fillna("Unknown",inplace=True)

In [28]:
#17. Remove duplicates based on OrderID.
data.drop_duplicates(subset="OrderID",inplace=True)

In [29]:
#18. Sort the data by TotalAmount in descending order.
data['TotalAmount'] = pd.to_numeric(data['TotalAmount'], errors='coerce')
data.sort_values(by='TotalAmount', ascending=False)

,OrderID,CustomerID,CustName,Product,Category,Quantity,Price,OrderDate,City,Region,Returned,TotalAmount
8548,43783,2261.0,@ eva !,Keyboard,Electronics,9.0,$1499.1,2024-05-23,PHOENIX#123,East,False,13491.90
363,98251,7329.0,@ alice !,Monitor,Accessories,9.0,$1499.09,2024-08-03,LOS ANGELES#123,West,False,13491.81
8512,70026,7539.0,@ charlie !,Phone,Electronics,9.0,$1499.07,2024-12-17,LOS ANGELES#123,East,False,13491.63
5631,92069,8101.0,@ bob !,Tablet,Electronics,9.0,$1499.05,2023-09-04,HOUSTON#123,North,True,13491.45
12639,95397,1935.0,@ david !,Tablet,Accessories,9.0,$1498.92,2023-11-22,LOS ANGELES#123,North,False,13490.28
...,...,...,...,...,...,...,...,...,...,...,...,...
43791,7003,2054.0,@ bob !,Laptop,Accessories,NaN,NaN,NaT,NEW YORK#123,East,False,NaN
43917,33744,2104.0,@ alice !,Monitor,Electronics,NaN,NaN,2023-09-17,LOS ANGELES#123,East,False,NaN
44087,96798,9523.0,@ eva !,Tablet,Electronics,NaN,NaN,2023-01-12,NEW YORK#123,North,False,NaN
44094,36440,9003.0,@ david !,Monitor,Accessories,NaN,NaN,2024-11-17,LOS ANGELES#123,North,False,NaN
44129,3136,NaN,NaN,NaN,NaN,NaN,NaN,NaT,Unknown,NaN,NaN,NaN

In [30]:
unique_orders = data.sort_values(by='TotalAmount', ascending=False).drop_duplicates(subset='OrderID')

# Now get the top 5 OrderIDs
top_5_unique_order_ids = unique_orders.head(5)['OrderID']

# Display the result
print(top_5_unique_order_ids)

8548     43783
363      98251
8512     70026
5631     92069
12639    95397
Name: OrderID, dtype: int64

In [31]:
#19. Get the top 5 orders with the highest total amount.

unique=data.sort_values(by='TotalAmount',ascending=False).drop_duplicates(subset="Product")
top_5=unique.head(5)['Product']
top_5

8548     Keyboard
363       Monitor
8512        Phone
5631       Tablet
36943      Laptop
Name: Product, dtype: object

In [32]:
#20. Extract year and month from OrderDate.

data['OrderDate'] = pd.to_datetime(data['OrderDate'])
data['Year'] = data['OrderDate'].dt.year
data['Month'] =data['OrderDate'].dt.month

In [33]:
 #21.Create a new column OrderMonth with full month names.
 data['OrderMonth'] = data['OrderDate'].dt.strftime('%B')
 data.head()

,OrderID,CustomerID,CustName,Product,Category,Quantity,Price,OrderDate,City,Region,Returned,TotalAmount,Year,Month,OrderMonth
0,44770,8192.0,@ charlie !,Keyboard,Electronics,1.0,$870.54,NaT,PHOENIX#123,South,False,870.54,NaN,NaN,NaN
1,23355,9138.0,@ charlie !,Monitor,Electronics,5.0,$144.02,2024-05-02,HOUSTON#123,West,False,720.10,2024.0,5.0,May
2,75847,4098.0,@ charlie !,Laptop,Accessories,3.0,$557.79,2024-11-08,NEW YORK#123,East,False,1673.37,2024.0,11.0,November
3,95176,2391.0,@ eva !,Monitor,Electronics,5.0,$552.2,NaT,CHICAGO#123,North,False,2761.00,NaN,NaN,NaN
4,1854,8842.0,@ eva !,Laptop,Accessories,4.0,$411.2,NaT,CHICAGO#123,East,False,1644.80,NaN,NaN,NaN

In [34]:
#22. Show all orders from Q1 of any year (Jan–Mar).
data[(data['Month'] >= 1) & (data['Month'] <= 3)]

,OrderID,CustomerID,CustName,Product,Category,Quantity,Price,OrderDate,City,Region,Returned,TotalAmount,Year,Month,OrderMonth
15,5103,1382.0,@ eva !,Phone,Accessories,1.0,$504.94,2023-03-07,NEW YORK#123,West,True,504.94,2023.0,3.0,March
21,87250,2818.0,@ alice !,Phone,Electronics,3.0,$1188.93,2024-02-27,LOS ANGELES#123,North,True,3566.79,2024.0,2.0,February
24,90538,2124.0,@ david !,Keyboard,Accessories,4.0,$898.16,2023-03-01,PHOENIX#123,West,False,3592.64,2023.0,3.0,March
43,48638,4913.0,@ charlie !,Tablet,Electronics,3.0,$330.45,2024-01-12,LOS ANGELES#123,East,False,991.35,2024.0,1.0,January
49,66090,6049.0,@ david !,Keyboard,Electronics,6.0,$822.84,2024-02-22,LOS ANGELES#123,South,False,4937.04,2024.0,2.0,February
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44104,61744,1720.0,@ charlie !,Laptop,Accessories,3.0,$914.03,2024-03-11,LOS ANGELES#123,South,False,2742.09,2024.0,3.0,March
44114,61043,9464.0,@ bob !,Tablet,Electronics,9.0,$1425.51,2024-02-15,CHICAGO#123,East,False,12829.59,2024.0,2.0,February
44115,29668,3306.0,@ david !,Keyboard,Accessories,8.0,$300.74,2023-02-17,HOUSTON#123,East,False,2405.92,2023.0,2.0,February
44118,37591,1436.0,@ charlie !,Laptop,Electronics,9.0,$966.02,2024-03-06,LOS ANGELES#123,South,False,8694.18,2024.0,3.0,March
44119,52690,8126.0,@ alice !,Keyboard,Accessories,9.0,$104.98,2023-01-09,LOS ANGELES#123,South,False,944.82,2023.0,1.0,January

In [35]:

#23.Count number of orders for each region.
data["Region"].value_counts()

Region
East     11102
North    11065
South    11031
West     10914
Name: count, dtype: int64

In [36]:
#24.Display all customers who bought both "Phone" and "Laptop".

ph= data[data['Product'] == 'Phone']['CustomerID'].unique()


la= data[data['Product'] == 'Laptop']['CustomerID'].unique()

both_p= set(ph) & set(la)

orders= data[data['CustomerID'].isin(both_p)]

# Display the filtered orders
orders

,OrderID,CustomerID,CustName,Product,Category,Quantity,Price,OrderDate,City,Region,Returned,TotalAmount,Year,Month,OrderMonth
2,75847,4098.0,@ charlie !,Laptop,Accessories,3.0,$557.79,2024-11-08,NEW YORK#123,East,False,1673.37,2024.0,11.0,November
3,95176,2391.0,@ eva !,Monitor,Electronics,5.0,$552.2,NaT,CHICAGO#123,North,False,2761.00,NaN,NaN,NaN
5,56788,6935.0,@ david !,Monitor,Electronics,1.0,$415.12,2024-10-06,LOS ANGELES#123,West,False,415.12,2024.0,10.0,October
6,63473,2787.0,@ bob !,Tablet,Electronics,3.0,$677.7,2024-04-03,PHOENIX#123,West,False,2033.10,2024.0,4.0,April
7,79506,3389.0,@ alice !,Phone,Accessories,9.0,$674.73,2024-07-14,HOUSTON#123,North,True,6072.57,2024.0,7.0,July
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44115,29668,3306.0,@ david !,Keyboard,Accessories,8.0,$300.74,2023-02-17,HOUSTON#123,East,False,2405.92,2023.0,2.0,February
44118,37591,1436.0,@ charlie !,Laptop,Electronics,9.0,$966.02,2024-03-06,LOS ANGELES#123,South,False,8694.18,2024.0,3.0,March
44121,41467,2545.0,@ david !,Keyboard,Electronics,6.0,$550.09,2023-04-03,CHICAGO#123,North,False,3300.54,2023.0,4.0,April
44122,78660,3353.0,@ david !,Laptop,Electronics,7.0,$306.59,NaT,PHOENIX#123,East,True,2146.13,NaN,NaN,NaN
44128,52233,2746.0,@ alice !,Laptop,Electronics,7.0,$1004.99,2023-12-21,LOS ANGELES#123,North,True,7034.93,2023.0,12.0,December

In [37]:
#25.Convert all city names to uppercase and restore them back.
data['City']=data['City'].str.upper()
data['City']=data['City'].str.title()

In [38]:
#26. Find average price of each category.
# Clean the 'Price' column by removing '$' and converting to numeric, coercing errors to NaN
data['Price'] = data['Price'].astype(str).str.replace('$', '', regex=False)
data['Price'] = pd.to_numeric(data['Price'], errors='coerce')

# Group by 'Category' and calculate the mean price
average_price_by_category = data.groupby('Category')['Price'].mean()

# Display the result
print(average_price_by_category)

Category
Accessories    800.719385
Electronics    799.233552
Name: Price, dtype: float64

In [39]:
#27.Use groupby() to find total sales by Region.
print(data.groupby('Region')['Price'].sum())

Region
East     8799027.91
North    8756119.54
South    8746617.39
West     8637566.72
Name: Price, dtype: float64

In [40]:
#28. Save only East region data to a CSV file.
east = data[data['Region'] == 'East']
east.to_csv('east_region_data.csv', index=False)

In [41]:
#29. Reset and set index using OrderID.
data.reset_index(drop=True, inplace=True)
data.set_index('OrderID', inplace=True)

In [42]:
 # 30.Display all orders placed on a weekend.
data['OrderDate'] = pd.to_datetime(data['OrderDate'])
data['DayOfWeek'] = data['OrderDate'].dt.day_name()
weekend_orders = data[data['DayOfWeek'].isin(['Saturday', 'Sunday'])]
print(weekend_orders)

         CustomerID     CustName   Product     Category  Quantity    Price  \
OrderID
56788        6935.0    @ david !   Monitor  Electronics       1.0   415.12
79506        3389.0    @ alice !     Phone  Accessories       9.0   674.73
55148        1287.0    @ david !    Laptop  Accessories       2.0   330.38
24564        3745.0      @ bob !    Tablet  Accessories       8.0   686.34
60114        6368.0    @ alice !    Laptop  Accessories       3.0   512.79
...             ...          ...       ...          ...       ...      ...
82024        1822.0    @ alice !    Tablet  Electronics       4.0  1140.16
28455        7859.0      @ bob !    Tablet  Electronics       2.0   634.68
47357        4279.0    @ david !    Tablet  Electronics       5.0   102.51
87538        9181.0  @ charlie !   Monitor          NaN       8.0   405.02
4013         1142.0      @ eva !  Keyboard  Electronics       6.0   960.80

         OrderDate             City Region Returned  TotalAmount    Year  \
OrderID
56788   2024-10-06  Los Angeles#123   West    False       415.12  2024.0
79506   2024-07-14      Houston#123  North     True      6072.57  2024.0
55148   2024-09-01      Houston#123   East    False       660.76  2024.0
24564   2023-04-23      Phoenix#123  North    False      5490.72  2023.0
60114   2023-08-05     New York#123  North    False      1538.37  2023.0
...            ...              ...    ...      ...          ...     ...
82024   2023-10-22      Houston#123  South    False      4560.64  2023.0
28455   2024-10-05      Houston#123   East    False      1269.36  2024.0
47357   2024-11-17      Houston#123  South     True       512.55  2024.0
87538   2023-08-27      Houston#123  North    False      3240.16  2023.0
4013    2023-12-10      Phoenix#123  North    False      5764.80  2023.0

         Month OrderMonth DayOfWeek
OrderID
56788     10.0    October    Sunday
79506      7.0       July    Sunday
55148      9.0  September    Sunday
24564      4.0      April    Sunday
60114      8.0     August  Saturday
...        ...        ...       ...
82024     10.0    October    Sunday
28455     10.0    October  Saturday
47357     11.0   November    Sunday
87538      8.0     August    Sunday
4013      12.0   December    Sunday

[10217 rows x 15 columns]

** Level 2 – Intermediate (31–60)**

In [43]:
#31.Create a pivot table of TotalAmount by Region and Category.
data.pivot_table('TotalAmount', index='Region', columns='Category', aggfunc='sum')*100

Category   Accessories   Electronics
Region
East      2.172558e+09  2.163991e+09
North     2.096259e+09  2.150394e+09
South     2.160293e+09  2.129432e+09
West      2.112383e+09  2.133142e+09

In [44]:
#32.Unpivot (melt) the pivot table from Task 31.
data.melt(id_vars=['Region', 'Category'], value_vars=['TotalAmount'], var_name='Metric', value_name='Value')

      Region     Category       Metric    Value
0      South  Electronics  TotalAmount   870.54
1       West  Electronics  TotalAmount   720.10
2       East  Accessories  TotalAmount  1673.37
3      North  Electronics  TotalAmount  2761.00
4       East  Accessories  TotalAmount  1644.80
...      ...          ...          ...      ...
44108  North          NaN  TotalAmount  3427.52
44109   East  Electronics  TotalAmount  6829.48
44110   East  Electronics  TotalAmount  3860.76
44111  North  Electronics  TotalAmount  7034.93
44112    NaN          NaN  TotalAmount      NaN

[44113 rows x 4 columns]

In [45]:
#33.Use groupby() to get average Price by Product and Region.
data.groupby(['Product', 'Region'])['Price'].mean()

Product   Region
Keyboard  East      803.876307
          North     791.026476
          South     798.904214
          West      781.515010
Laptop    East      790.636040
          North     820.579027
          South     800.771452
          West      808.938738
Monitor   East      797.645760
          North     792.057947
          South     789.226825
          West      805.042030
Phone     East      796.699590
          North     793.319238
          South     811.371740
          West      794.590221
Tablet    East      821.558164
          North     809.066328
          South     801.822212
          West      803.219359
Name: Price, dtype: float64

In [46]:
#34.Use .agg() to get min, max, and mean quantity for each category.
data.groupby('Category')['Quantity'].agg(['min', 'max', 'mean'])

             min  max      mean
Category
Accessories  1.0  9.0  4.998734
Electronics  1.0  9.0  4.983833

In [47]:
#35.Create a lookup table for CustomerID and CustomerName and remove duplicates.

lookup_table = data[['CustomerID', 'CustName']].drop_duplicates()

print(lookup_table)

         CustomerID     CustName
OrderID
44770        8192.0  @ charlie !
23355        9138.0  @ charlie !
75847        4098.0  @ charlie !
95176        2391.0      @ eva !
1854         8842.0      @ eva !
...             ...          ...
78660        3353.0    @ david !
13142        1256.0      @ bob !
47952        8896.0    @ alice !
48434        1731.0      @ eva !
3136            NaN          NaN

[28165 rows x 2 columns]

In [48]:
#36. Create a lookup for Product and Category, remove duplicates.
lookup_table = data[['Product', 'Category']].drop_duplicates()

print(lookup_table)

          Product     Category
OrderID
44770    Keyboard  Electronics
23355     Monitor  Electronics
75847      Laptop  Accessories
63473      Tablet  Electronics
79506       Phone  Accessories
24564      Tablet  Accessories
36423      Laptop  Electronics
13329    Keyboard  Accessories
87250       Phone  Electronics
86704     Monitor  Accessories
3622      Monitor          NaN
61985         NaN  Accessories
49140         NaN  Electronics
26070      Tablet          NaN
53242    Keyboard          NaN
37358      Laptop          NaN
38979       Phone          NaN
15972         NaN          NaN

In [49]:

#37.Merge back the lookups with the main file (simulate master lookup join).
data=data.merge(lookup_table,on=['Product','Category'],how='left')
data.head()

,CustomerID,CustName,Product,Category,Quantity,Price,OrderDate,City,Region,Returned,TotalAmount,Year,Month,OrderMonth,DayOfWeek
0,8192.0,@ charlie !,Keyboard,Electronics,1.0,870.54,NaT,Phoenix#123,South,False,870.54,NaN,NaN,NaN,NaN
1,9138.0,@ charlie !,Monitor,Electronics,5.0,144.02,2024-05-02,Houston#123,West,False,720.10,2024.0,5.0,May,Thursday
2,4098.0,@ charlie !,Laptop,Accessories,3.0,557.79,2024-11-08,New York#123,East,False,1673.37,2024.0,11.0,November,Friday
3,2391.0,@ eva !,Monitor,Electronics,5.0,552.20,NaT,Chicago#123,North,False,2761.00,NaN,NaN,NaN,NaN
4,8842.0,@ eva !,Laptop,Accessories,4.0,411.20,NaT,Chicago#123,East,False,1644.80,NaN,NaN,NaN,NaN

In [50]:
#38.Compare the original and merged DataFrames – are all rows retained?

In [51]:
# 39.Calculate return rate % by region (total returned orders / total orders).

**Level 3 – Advanced Pandas Tasks (61–90)**

** Data Transformations & Aggregations**

In [52]:
# 51.Create a new column DiscountedPrice assuming a flat 10% discount on all products.

data['DiscountedPrice'] = data['Price'] * 0.9
data['DiscountedPrice']

0         783.486
1         129.618
2         502.011
3         496.980
4         370.080
           ...
44108     771.192
44109     878.076
44110    1158.228
44111     904.491
44112         NaN
Name: DiscountedPrice, Length: 44113, dtype: float64

In [53]:
# 52.Use .rolling() to calculate a 7-day rolling average of TotalAmount per city.

In [54]:
#53.Calculate the cumulative revenue for each Region sorted by OrderDate.
data['TotalAmount'] = pd.to_numeric(data['TotalAmount'], errors='coerce')
data.groupby(['Region', 'OrderDate'])['TotalAmount'].cumsum()

0             NaN
1          720.10
2         1673.37
3             NaN
4             NaN
           ...
44108         NaN
44109    56937.30
44110    71962.17
44111    35913.64
44112         NaN
Name: TotalAmount, Length: 44113, dtype: float64

In [55]:
#54. Rank customers by their total revenue generated (TotalAmount) in descending order.

Rank=data.groupby('CustomerID')['TotalAmount'].sum().reset_index()
Rank['Rank'] = Rank['TotalAmount'].rank(ascending=False)
Rank.sort_values(by='Rank')

      CustomerID  TotalAmount    Rank
4453      5490.0     80137.79     1.0
5193      6237.0     74345.48     2.0
8929      9998.0     70750.86     3.0
7663      8727.0     66356.81     4.0
6275      7328.0     66228.47     5.0
...          ...          ...     ...
2554      3571.0       120.36  8926.0
4818      5859.0         0.00  8928.5
4608      5647.0         0.00  8928.5
5791      6841.0         0.00  8928.5
2626      3643.0         0.00  8928.5

[8930 rows x 3 columns]

In [56]:
# 55.Calculate the average order value per customer using groupby().
data.groupby('CustomerID')['TotalAmount'].mean()

CustomerID
1000.0    2636.940000
1001.0    3574.795000
1002.0    2786.690000
1003.0    3788.040000
1004.0    1345.543333
             ...
9994.0    3960.805714
9995.0    3883.618000
9996.0    4013.054000
9997.0    1842.432500
9998.0    7075.086000
Name: TotalAmount, Length: 8930, dtype: float64

In [57]:
data.head()

,CustomerID,CustName,Product,Category,Quantity,Price,OrderDate,City,Region,Returned,TotalAmount,Year,Month,OrderMonth,DayOfWeek,DiscountedPrice
0,8192.0,@ charlie !,Keyboard,Electronics,1.0,870.54,NaT,Phoenix#123,South,False,870.54,NaN,NaN,NaN,NaN,783.486
1,9138.0,@ charlie !,Monitor,Electronics,5.0,144.02,2024-05-02,Houston#123,West,False,720.10,2024.0,5.0,May,Thursday,129.618
2,4098.0,@ charlie !,Laptop,Accessories,3.0,557.79,2024-11-08,New York#123,East,False,1673.37,2024.0,11.0,November,Friday,502.011
3,2391.0,@ eva !,Monitor,Electronics,5.0,552.20,NaT,Chicago#123,North,False,2761.00,NaN,NaN,NaN,NaN,496.980
4,8842.0,@ eva !,Laptop,Accessories,4.0,411.20,NaT,Chicago#123,East,False,1644.80,NaN,NaN,NaN,NaN,370.080

In [58]:
#56. Generate a report showing total quantity sold per Category per region
data.groupby(['Category', 'Region'])['Quantity'].sum()

Category     Region
Accessories  East      27206.0
             North     26353.0
             South     26977.0
             West      26072.0
Electronics  East      26736.0
             North     26801.0
             South     26675.0
             West      26761.0
Name: Quantity, dtype: float64

In [59]:
#57.Use .agg() to compute multiple stats (sum, mean, min, max) for TotalAmount per Region.

data.groupby('Region')['TotalAmount'].agg(['min','sum','mean','max'])

           min          sum         mean       max
Region
East    100.36  44097309.91  4015.051435  13491.90
North   100.19  43460883.90  3972.295393  13491.45
South   101.10  43810145.82  4007.514254  13488.12
West    100.34  43353363.41  4010.486902  13491.81

In [60]:
#58.Create a summary DataFrame showing each customer’s: total orders, total amount spent, and total products bought.
data.groupby(['Quantity','TotalAmount','Product'])[('CustName')].sum()

Quantity  TotalAmount  Product
1.0       100.19       Tablet        @ david !
          100.34       Monitor       @ david !
          100.36       Phone         @ david !
          100.85       Phone         @ alice !
          100.89       Tablet        @ alice !
                                      ...
9.0       13490.28     Tablet        @ david !
          13491.45     Tablet          @ bob !
          13491.63     Phone       @ charlie !
          13491.81     Monitor       @ alice !
          13491.90     Keyboard        @ eva !
Name: CustName, Length: 42628, dtype: object

** Time Series & Date Handling**

In [61]:
# 59.Convert the OrderDate to datetime and extract new columns: Year, Month, and Weekday.

data['OrderDate'] = pd.to_datetime(data['OrderDate'])
data['Year'] = data['OrderDate'].dt.year
data['Month'] = data['OrderDate'].dt.month
data['Weekday'] = data['OrderDate'].dt.day_name()
data[['Year','Month','Weekday']].head()

     Year  Month   Weekday
0     NaN    NaN       NaN
1  2024.0    5.0  Thursday
2  2024.0   11.0    Friday
3     NaN    NaN       NaN
4     NaN    NaN       NaN

In [62]:
#60.Create a monthly revenue trend using resample() on OrderDate.
data['TotalAmount'] = pd.to_numeric(data['TotalAmount'], errors='coerce')
monthly_revenue = data.resample('M', on='OrderDate')['TotalAmount'].sum()
monthly_revenue

/tmp/ipython-input-2157242896.py:3: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  monthly_revenue = data.resample('M', on='OrderDate')['TotalAmount'].sum()

OrderDate
2023-01-31    6123923.45
2023-02-28    5088756.22
2023-03-31    5852320.62
2023-04-30    5758866.68
2023-05-31    6242572.69
2023-06-30    5615805.11
2023-07-31    5938955.11
2023-08-31    5946993.54
2023-09-30    5581825.87
2023-10-31    5976885.67
2023-11-30    5691476.84
2023-12-31    5977062.50
2024-01-31    5831897.33
2024-02-29    5469119.98
2024-03-31    5711458.43
2024-04-30    5543404.51
2024-05-31    5873494.09
2024-06-30    6169657.01
2024-07-31    5963667.94
2024-08-31    6020216.53
2024-09-30    5709287.65
2024-10-31    5800434.49
2024-11-30    5617249.60
2024-12-31    6116450.40
Name: TotalAmount, dtype: float64

In [63]:
#61. Find the day of the week with the highest sales volume.

print(data.groupby('Weekday')['TotalAmount'].sum().sort_values(ascending=False).head(1))

Weekday
Saturday    20366639.04
Name: TotalAmount, dtype: float64

In [64]:
data.head()

,CustomerID,CustName,Product,Category,Quantity,Price,OrderDate,City,Region,Returned,TotalAmount,Year,Month,OrderMonth,DayOfWeek,DiscountedPrice,Weekday
0,8192.0,@ charlie !,Keyboard,Electronics,1.0,870.54,NaT,Phoenix#123,South,False,870.54,NaN,NaN,NaN,NaN,783.486,NaN
1,9138.0,@ charlie !,Monitor,Electronics,5.0,144.02,2024-05-02,Houston#123,West,False,720.10,2024.0,5.0,May,Thursday,129.618,Thursday
2,4098.0,@ charlie !,Laptop,Accessories,3.0,557.79,2024-11-08,New York#123,East,False,1673.37,2024.0,11.0,November,Friday,502.011,Friday
3,2391.0,@ eva !,Monitor,Electronics,5.0,552.20,NaT,Chicago#123,North,False,2761.00,NaN,NaN,NaN,NaN,496.980,NaN
4,8842.0,@ eva !,Laptop,Accessories,4.0,411.20,NaT,Chicago#123,East,False,1644.80,NaN,NaN,NaN,NaN,370.080,NaN

In [65]:
#62.Compare monthly returned orders count vs. total orders.

In [66]:
#63. Find peak sales month and peak returned month for each Region.

In [67]:
#64. Identify cities that saw consistent monthly growth for 3+ months in a row.

In [68]:
#65. Generate a YoY (Year-over-Year) growth percentage in TotalAmount for each Region


yearly_sales = data.groupby(['Region', 'Year'])['TotalAmount'].sum().unstack()
print(yearly_sales.pct_change(axis=1) * 100)

Year    2023.0    2024.0
Region
East       NaN -3.866878
North      NaN  2.226061
South      NaN  5.242899
West       NaN -3.130075

** String & Conditional Logic**

In [85]:
#66. Extract only the first name from the CustomerName column.
data['FirstName'] = data['CustName'].str.extract(r'(\w+)', expand=False)
print(data[['CustName', 'FirstName']].head())

      CustName FirstName
0  @ charlie !   charlie
1  @ charlie !   charlie
2  @ charlie !   charlie
3      @ eva !       eva
4      @ eva !       eva

In [89]:
#77.Create a column HighValueOrder where TotalAmount > 5000.

data['HighValueOrder'] = data['TotalAmount'] > 5000
data.head()

,CustomerID,CustName,Product,Category,Quantity,Price,OrderDate,City,Region,Returned,TotalAmount,Year,Month,OrderMonth,DayOfWeek,DiscountedPrice,Weekday,FirstName,HighValueOrder
0,8192.0,@ charlie !,Keyboard,Electronics,1.0,870.54,NaT,Phoenix#123,South,False,870.54,NaN,NaN,NaN,NaN,783.486,NaN,charlie,False
1,9138.0,@ charlie !,Monitor,Electronics,5.0,144.02,2024-05-02,Houston#123,West,False,720.10,2024.0,5.0,May,Thursday,129.618,Thursday,charlie,False
2,4098.0,@ charlie !,Laptop,Accessories,3.0,557.79,2024-11-08,New York#123,East,False,1673.37,2024.0,11.0,November,Friday,502.011,Friday,charlie,False
3,2391.0,@ eva !,Monitor,Electronics,5.0,552.20,NaT,Chicago#123,North,False,2761.00,NaN,NaN,NaN,NaN,496.980,NaN,eva,False
4,8842.0,@ eva !,Laptop,Accessories,4.0,411.20,NaT,Chicago#123,East,False,1644.80,NaN,NaN,NaN,NaN,370.080,NaN,eva,False

In [96]:
#78. Flag suspicious orders where Quantity > 10 and Price > 1000.
data['Suspicious'] = (data['Quantity'] > 10) & (data['Price'] > 1000)

In [97]:
#79. Normalize all text columns (lowercase, strip spaces, remove special chars if any).
text_cols = data.select_dtypes(include='object').columns
for col in text_cols:
    data[col] = data[col].str.lower().str.strip().str.replace(r'[^\w\s]', '', regex=True)

AttributeError: Can only use .str accessor with string values!

In [98]:
#80. Filter all products that contain the substring 'top' (case insensitive).


print(data[data['Product'].str.contains('top', case=False, na=False)])

       CustomerID   CustName Product     Category  Quantity    Price  \
2          4098.0   charlie   laptop  accessories       3.0   557.79
4          8842.0       eva   laptop  accessories       4.0   411.20
8          1287.0     david   laptop  accessories       2.0   330.38
10         6368.0     alice   laptop  accessories       3.0   512.79
11         6745.0   charlie   laptop  electronics       4.0   188.80
...           ...        ...     ...          ...       ...      ...
44085      7327.0     david   laptop  electronics       6.0  1251.61
44087      1720.0   charlie   laptop  accessories       3.0   914.03
44101      1436.0   charlie   laptop  electronics       9.0   966.02
44105      3353.0     david   laptop  electronics       7.0   306.59
44111      2746.0     alice   laptop  electronics       7.0  1004.99

       OrderDate            City Region Returned  TotalAmount    Year  Month  \
2     2024-11-08     new york123   east    False      1673.37  2024.0   11.0
4            NaT      chicago123   east    False      1644.80     NaN    NaN
8     2024-09-01      houston123   east    False       660.76  2024.0    9.0
10    2023-08-05     new york123  north    False      1538.37  2023.0    8.0
11    2023-10-14      houston123   east    False       755.20  2023.0   10.0
...          ...             ...    ...      ...          ...     ...    ...
44085        NaT      houston123  north    False      7509.66     NaN    NaN
44087 2024-03-11  los angeles123  south    False      2742.09  2024.0    3.0
44101 2024-03-06  los angeles123  south    False      8694.18  2024.0    3.0
44105        NaT      phoenix123   east     True      2146.13     NaN    NaN
44111 2023-12-21  los angeles123  north     True      7034.93  2023.0   12.0

      OrderMonth  DayOfWeek  DiscountedPrice    Weekday FirstName  \
2       November     Friday          502.011     Friday   charlie
4            NaN        NaN          370.080        NaN       eva
8      September     Sunday          297.342     Sunday     david
10        August   Saturday          461.511   Saturday     alice
11       October   Saturday          169.920   Saturday   charlie
...          ...        ...              ...        ...       ...
44085        NaN        NaN         1126.449        NaN     david
44087      March     Monday          822.627     Monday   charlie
44101      March  Wednesday          869.418  Wednesday   charlie
44105        NaN        NaN          275.931        NaN     david
44111   December   Thursday          904.491   Thursday     alice

       HighValueOrder  Suspicious
2               False       False
4               False       False
8               False       False
10              False       False
11              False       False
...               ...         ...
44085            True       False
44087           False       False
44101            True       False
44105           False       False
44111            True       False

[8677 rows x 20 columns]

In [99]:
# 81.Use pivot_table() to summarize TotalAmount by Region and Category.


pivot_81 = pd.pivot_table(data, values='TotalAmount', index='Region', columns='Category', aggfunc='sum')
print(pivot_81)

Category  accessories  electronics
Region
east      21725578.44  21639912.65
north     20962586.65  21503940.37
south     21602929.31  21294318.93
west      21123830.98  21331419.60

In [100]:
#82.Create a column to show each order's percentage of the total monthly revenue.



monthly_total = data.groupby([data['OrderDate'].dt.to_period('M')])['TotalAmount'].transform('sum')
data['MonthlyRevenue%'] = (data['TotalAmount'] / monthly_total) * 100

In [101]:
#83.Use .transform() to normalize TotalAmount within each Region.

data['NormalizedTotal'] = data.groupby('Region')['TotalAmount'].transform(lambda x: (x - x.mean()) / x.std())

In [77]:
#84. Perform one-hot encoding of the Region column.

In [102]:
#85. Generate a heatmap-ready table using pivot_table() showing quantity sold by City and Product.

heatmap_table = data.pivot_table(values='Quantity', index='City', columns='Product', aggfunc='sum')
print(heatmap_table)

Product         keyboard  laptop  monitor   phone  tablet
City
chicago123        8450.0  8078.0   8326.0  8750.0  8363.0
houston123        8526.0  8443.0   8466.0  8212.0  8155.0
los angeles123    8073.0  8339.0   8135.0  8233.0  8356.0
new york123       8500.0  8517.0   8233.0  8827.0  7877.0
phoenix123        8638.0  8621.0   8066.0  8606.0  8796.0
unknown            752.0   768.0    795.0   776.0   776.0

*** Merging and Lookup Files (Master File Creation)***

In [106]:
#86.Create a customer lookup DataFrame with unique CustomerID, CustomerName, and total orders. Save it.

customer_summary = data.groupby(['CustomerID', 'CustName']).agg(TotalOrders=('Product', 'count')).reset_index()
customer_summary.to_csv("Customer_Lookup.csv", index=False)

In [107]:
#87.Create a product lookup DataFrame with unique Product, Category, and average Price.


product_summary = data.groupby(['Product', 'Category']).agg(AvgPrice=('Price', 'mean')).reset_index()
product_summary.to_csv("Product_Lookup.csv", index=False)

In [109]:
#88.Merge the original Sales_100k_Dataset.csv with both the customer and product lookup


data = data.merge(customer_summary, on=['CustomerID', 'CustName'], how='left')
data = data.merge(product_summary, on=['Product', 'Category'], how='left')

In [110]:
#89. After merge, create a master file with these columns: OrderID, OrderDate,CustomerName, Product, Category, Price, Quantity, TotalAmount, Returned, and the AvgProductPrice and TotalCustomerOrders from lookup tables.

In [112]:
#90. Analyze and visualize the top 5 customers and top 5 products contributing to revenue


top_customers = data.groupby('CustName')['TotalAmount'].sum().sort_values(ascending=False).head(5)
top_products = data.groupby('Product')['TotalAmount'].sum().sort_values(ascending=False).head(5)
print(top_customers)
print(top_products)

CustName
bob         35941297.45
david       35133244.71
eva         34874742.30
alice       34468902.47
charlie     34303516.11
Name: TotalAmount, dtype: float64
Product
phone       34701014.80
laptop      34537414.28
tablet      34272667.68
keyboard    34176222.85
monitor     33619265.20
Name: TotalAmount, dtype: float64

In [105]:
data.head()

,CustomerID,CustName,Product,Category,Quantity,Price,OrderDate,City,Region,Returned,...,Month,OrderMonth,DayOfWeek,DiscountedPrice,Weekday,FirstName,HighValueOrder,Suspicious,MonthlyRevenue%,NormalizedTotal
0,8192.0,charlie,keyboard,electronics,1.0,870.54,NaT,phoenix123,south,False,...,NaN,NaN,NaN,783.486,NaN,charlie,False,False,NaN,-1.020377
1,9138.0,charlie,monitor,electronics,5.0,144.02,2024-05-02,houston123,west,False,...,5.0,May,Thursday,129.618,Thursday,charlie,False,False,0.01226,-1.069263
2,4098.0,charlie,laptop,accessories,3.0,557.79,2024-11-08,new york123,east,False,...,11.0,November,Friday,502.011,Friday,charlie,False,False,0.02979,-0.754658
3,2391.0,eva,monitor,electronics,5.0,552.20,NaT,chicago123,north,False,...,NaN,NaN,NaN,496.980,NaN,eva,False,False,NaN,-0.396121
4,8842.0,eva,laptop,accessories,4.0,411.20,NaT,chicago123,east,False,...,NaN,NaN,NaN,370.080,NaN,eva,False,False,NaN,-0.763866